### ISSUE TITLE
Help with error 

### ISSUE THREAD

**Issue by jimgsey** [TheParasiteProject-Devices/packages_apps_XiaomiParts#1]
`cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "out/soong"     --out "out"     --soong_variables out/soong/soong.lineage_sweet.variables -o out/soong/build.lineage_sweet.ninja --globListDir lineage_sweet --globFile out/soong/globs-lineage_sweet.ninja -l out/.module_paths/Android.bp.list --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used.lineage_sweet.build Android.bp
error: packages/apps/XiaomiParts/packages/devicesettings/Android.bp:5:1: "DeviceSettings" depends on undefined module "com.github.bumptech.glide_glide".
Or did you mean ["incompatibilities.api.public.29" "incompatibilities.api.public.30" "incompatibilities.api.system.29" "incompatibilities.api.system.30" "libcom.android.sysprop.bluetooth" "libcom.android.sysprop.watchdog" "test_com.android.neuralnetworks"]?
error: packages/apps/XiaomiParts/packages/doze/Android.bp:4:1: "DeviceDoze" depends on undefined module "com.github.bumptech.glide_glide".
Or did you mean ["incompatibilities.api.public.29" "incompatibilities.api.public.30" "incompatibilities.api.system.29" "incompatibilities.api.system.30" "libcom.android.sysprop.bluetooth" "libcom.android.sysprop.watchdog" "test_com.android.neuralnetworks"]?
fatal errors encountered
ninja: build stopped: subcommand failed.
12:39:54 soong bootstrap failed with: exit status 1`

**Comment by someone5678** [comment]
This package is no longer supported
